import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/styles/globals.scss';

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  // display: 'swap',
});

export const metadata: Metadata = {
  title: 'Yard Sale',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
