import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import List from '@/components/List';

const inter = Inter({ subsets: ['latin'] });

const Home = () => (
  <>
    <Head>
      <title>Yard Sale</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main} ${inter.className}`}>
      <header className={styles.coverImage}>

      </header>
      <List />
    </main>
  </>
);

export default Home;
